popular_brands = {
    'Toyota': ['тойота', 'toyota'],
    'Honda': ['хонда', 'honda'],
    'Ford': ['форд', 'ford'],
    'Chevrolet': ['шевроле', 'chevrolet'],
    'Nissan': ['нисан', 'nissan'],
    'BMW': ['бмв', 'bmw'],
    'Mercedes-Benz': ['мерседес', 'mercedes-benz','мерс', 'мерин','mercedes'],
    'Volkswagen': ['фольксваген', 'volkswagen'],
    'Hyundai': ['хендай', 'hyundai'],
    'Kia': ['киа', 'kia'],
    'Audi': ['ауди', 'audi'],
    'Lexus': ['лексус', 'lexus'],
    'Mazda': ['мазда', 'mazda'],
    'Subaru': ['субару', 'subaru'],
    'Volvo': ['вольво', 'volvo'],
    'Mitsubishi': ['митсубиси', 'mitsubishi'],
    'Porsche': ['порше', 'porsche'],
    'Land Rover': ['ленд ровер', 'land rover'],
    'Jaguar': ['ягуар', 'jaguar'],
    'Fiat': ['фиат', 'fiat'],
    'Renault': ['рено', 'renault'],
    'Peugeot': ['пежо', 'peugeot'],
    'Citroen': ['ситроен', 'citroen'],
    'Suzuki': ['сузуки', 'suzuki'],
    'Infiniti': ['инфинити', 'infiniti'],
    'Acura': ['акура', 'acura'],
    'Tesla': ['тесла', 'tesla'],
    'Chrysler': ['крайслер', 'chrysler'],
    'Dodge': ['додж', 'dodge'],
    'Jeep': ['джип', 'jeep']
}